namespace ClaudeRTL;

/// <summary>
/// Safe wrapper around WinSparkle. Every native call is guarded so a missing or
/// incompatible WinSparkle.dll can never crash the app — failures are logged to crash.log.
/// </summary>
internal static class UpdateService
{
    private const string AppcastUrl = "https://claude-rtl.grwlab.net/appcast-win.xml";

    private const string CompanyName = "GRW Lab";
    private const string AppName = "Claude RTL";
    private const int CheckIntervalSeconds = 86400; // 24 hours

    // EdDSA (Ed25519) public key in base64. Replace the placeholder with the real
    // key generated by `winsparkle/tools/generate_keys`. While it stays the
    // placeholder the key is not registered (updates remain unverified/disabled).
    private const string PublicKeyPlaceholder = "__WINSPARKLE_PUBKEY__";
    private const string PublicKey = "__WINSPARKLE_PUBKEY__";

    private static readonly object Sync = new();
    private static bool _initialized;

    public static void Initialize()
    {
        lock (Sync)
        {
            if (_initialized)
                return;

            try
            {
                WinSparkleInterop.win_sparkle_set_appcast_url(AppcastUrl);

                if (PublicKey != PublicKeyPlaceholder)
                    WinSparkleInterop.win_sparkle_set_eddsa_public_key(PublicKey);

                WinSparkleInterop.win_sparkle_set_app_details(CompanyName, AppName, Settings.VersionLabel());
                WinSparkleInterop.win_sparkle_set_automatic_check_for_updates(
                    Settings.Instance.AutoCheckForUpdates ? 1 : 0);
                WinSparkleInterop.win_sparkle_set_update_check_interval(CheckIntervalSeconds);
                WinSparkleInterop.win_sparkle_init();

                _initialized = true;
            }
            catch (Exception ex)
            {
                CrashLogger.Log("UpdateService.Initialize", ex);
            }
        }
    }

    public static void CheckNow()
    {
        try
        {
            if (!_initialized)
                Initialize();

            WinSparkleInterop.win_sparkle_check_update_with_ui();
        }
        catch (Exception ex)
        {
            CrashLogger.Log("UpdateService.CheckNow", ex);
        }
    }

    public static void SetAutomaticCheck(bool enabled)
    {
        try
        {
            WinSparkleInterop.win_sparkle_set_automatic_check_for_updates(enabled ? 1 : 0);
        }
        catch (Exception ex)
        {
            CrashLogger.Log("UpdateService.SetAutomaticCheck", ex);
        }
    }

    public static void Shutdown()
    {
        lock (Sync)
        {
            if (!_initialized)
                return;

            try
            {
                WinSparkleInterop.win_sparkle_cleanup();
            }
            catch (Exception ex)
            {
                CrashLogger.Log("UpdateService.Shutdown", ex);
            }
            finally
            {
                _initialized = false;
            }
        }
    }
}
